[package]
authors = ["Jan Tojnar <jtojnar@gmail.com>"]
name = "patronus-enchant"
version = "0.2.0"

[dependencies]
enchant = "0.2"
patronus-provider = {path = "../../patronus-provider"}

[lib]
crate-type = ["cdylib"]
