[package]
authors = ["Jan Tojnar <jtojnar@gmail.com>"]
name = "patronus-languagetool"
version = "0.1.1"

[dependencies]
config = "0.9"
languagetool = "0.1"
patronus-provider = {path = "../../patronus-provider"}
xdg = "2.2"

[lib]
crate-type = ["cdylib"]
