[package]
authors = ["Jan Tojnar <jtojnar@gmail.com>"]
build = "build.rs"
name = "patronus-capi"
version = "0.1.0"

[dependencies]
patronus = {path = "../patronus"}
patronus-provider = {path = "../patronus-provider"}

[build-dependencies]
moz-cheddar = "0.4"

[lib]
crate-type = ["cdylib"]
